version: "3.9"
services:
  redes-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: redes-server
    container_name: redes-server
#    env_file: .env
#    environment:
#      - DB_HOST=postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - modules:/app/node_modules

volumes:
  modules:
